package me.nixuge.towers.world;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map.Entry;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.Chest;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

import lombok.val;

public class ChestManager {
    public final static HashMap<Location, ItemStack[]> chests = new HashMap<>();
    public final static World world = Bukkit.getWorld("world");
    static {
        val w = world;
        chests.put(new Location(w, -52, 192, 6),   new ItemStack[]{new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 14), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1)});
        chests.put(new Location(w, 52, 192, -6),   new ItemStack[]{new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.SANDSTONE, 64), new ItemStack(Material.STAINED_CLAY, 64, (byte) 11), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1), new ItemStack(Material.WOOD, 64, (byte) 1)});
        chests.put(new Location(w, 56, 192, -8),   new ItemStack[]{new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32)});
        chests.put(new Location(w, -56, 192, 8),   new ItemStack[]{new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.SPRUCE_FENCE, 64), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.STRING, 32), new ItemStack(Material.LADDER, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32), new ItemStack(Material.BAKED_POTATO, 32)});
        chests.put(new Location(w, 56, 192, -6),   new ItemStack[]{new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), null, null, null, null, null, null, null, null, null, new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8)});
        chests.put(new Location(w, -56, 192, 6),   new ItemStack[]{new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), new ItemStack(Material.BOW, 1), null, null, null, null, null, null, null, null, null, new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8), new ItemStack(Material.ARROW, 8)});
        chests.put(new Location(w, -52, 192, 8),   new ItemStack[]{new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64)});
        chests.put(new Location(w, 52, 192, -8),   new ItemStack[]{new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.COBBLESTONE, 64), new ItemStack(Material.WOOD, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64), new ItemStack(Material.STICK, 64)});
        chests.put(new Location(w, -56, 192, -7),    new ItemStack[]{new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOK, 8), new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.BOOK, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8), new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.ENCHANTMENT_TABLE, 1), new ItemStack(Material.BOOKSHELF, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8), new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOK, 8), new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.BOOK, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8)});
        chests.put(new Location(w, 56, 192, 7),  new ItemStack[]{new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOK, 8), new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.BOOK, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8), new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.ENCHANTMENT_TABLE, 1), new ItemStack(Material.BOOKSHELF, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8), new ItemStack(Material.EXP_BOTTLE, 8), null, null, new ItemStack(Material.BOOK, 8), new ItemStack(Material.BOOKSHELF, 8), new ItemStack(Material.BOOK, 8), null, null, new ItemStack(Material.EXP_BOTTLE, 8)});
        chests.put(new Location(w, -52, 192, -7),    new ItemStack[]{applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 1), null, null, null, new ItemStack(Material.ANVIL, 1), null, null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.THORNS, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 4), null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DURABILITY, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 1), null, null, null, new ItemStack(Material.ANVIL, 1), null, null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_FALL, 3)});
        chests.put(new Location(w, 52, 192, 7),  new ItemStack[]{applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 1), null, null, null, new ItemStack(Material.ANVIL, 1), null, null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.THORNS, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 4), null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DURABILITY, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 1), null, null, null, new ItemStack(Material.ANVIL, 1), null, null, null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_FALL, 3)});
        chests.put(new Location(w, -54, 192, -14),   new ItemStack[]{new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.DETECTOR_RAIL, 32), new ItemStack(Material.DETECTOR_RAIL, 32), new ItemStack(Material.DETECTOR_RAIL, 32), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), new ItemStack(Material.TNT, 1), new ItemStack(Material.EXPLOSIVE_MINECART, 1), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), null});
        chests.put(new Location(w, 54, 192, 14), new ItemStack[]{new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.POWERED_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.ACTIVATOR_RAIL, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.RAILS, 32), new ItemStack(Material.DETECTOR_RAIL, 32), new ItemStack(Material.DETECTOR_RAIL, 32), new ItemStack(Material.DETECTOR_RAIL, 32), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), new ItemStack(Material.TNT, 1), new ItemStack(Material.EXPLOSIVE_MINECART, 1), null, new ItemStack(Material.EXPLOSIVE_MINECART, 1), null});
        chests.put(new Location(w, -40, 192, -14),   new ItemStack[]{new ItemStack(Material.FIREBALL, 3), null, null, null, new ItemStack(Material.DISPENSER, 16), null, null, null, new ItemStack(Material.FIREBALL, 3), new ItemStack(Material.FIREBALL, 3), null, null, null, null, null, null, null, new ItemStack(Material.FIREBALL, 3), new ItemStack(Material.FIREBALL, 3), null, null, null, new ItemStack(Material.TRIPWIRE_HOOK, 64), null, null, null, new ItemStack(Material.FIREBALL, 3)});
        chests.put(new Location(w, 40, 192, 14), new ItemStack[]{new ItemStack(Material.FIREBALL, 3), null, null, null, new ItemStack(Material.DISPENSER, 16), null, null, null, new ItemStack(Material.FIREBALL, 3), new ItemStack(Material.FIREBALL, 3), null, null, null, null, null, null, null, new ItemStack(Material.FIREBALL, 3), new ItemStack(Material.FIREBALL, 3), null, null, null, new ItemStack(Material.TRIPWIRE_HOOK, 64), null, null, null, new ItemStack(Material.FIREBALL, 3)});
        chests.put(new Location(w, -26, 197, -14),   new ItemStack[]{new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1)});
        chests.put(new Location(w, 26, 197, 14), new ItemStack[]{new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.GOLDEN_APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1), new ItemStack(Material.APPLE, 1)});
        chests.put(new Location(w, -54, 197, 14),  new ItemStack[]{null, null, null, null, null, null, null, null, null, null, null, null, null, new ItemStack(Material.FISHING_ROD, 1), null, new ItemStack(Material.EGG, 4), null, null, null, null, new ItemStack(Material.SNOW_BALL, 4), null, null, null, null, null, null});
        chests.put(new Location(w, 54, 197, -14),  new ItemStack[]{null, null, null, null, null, null, null, null, null, null, null, null, null, new ItemStack(Material.FISHING_ROD, 1), null, new ItemStack(Material.EGG, 4), null, null, null, null, new ItemStack(Material.SNOW_BALL, 4), null, null, null, null, null, null});
        chests.put(new Location(w, -40, 197, 14),  new ItemStack[]{null, null, new ItemStack(Material.STONE_SWORD, 1) , null, new ItemStack(Material.MILK_BUCKET, 1), null, new ItemStack(Material.STONE_SWORD, 1) , null, null, null, new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , null, null, null, new ItemStack(Material.STONE_SWORD, 1) , null, new ItemStack(Material.MILK_BUCKET, 1), null, new ItemStack(Material.STONE_SWORD, 1) , null, null});
        chests.put(new Location(w, 40, 197, -14),  new ItemStack[]{null, null, new ItemStack(Material.STONE_SWORD, 1) , null, new ItemStack(Material.MILK_BUCKET, 1), null, new ItemStack(Material.STONE_SWORD, 1) , null, null, null, new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , new ItemStack(Material.STONE_SWORD, 1) , null, null, null, new ItemStack(Material.STONE_SWORD, 1) , null, new ItemStack(Material.MILK_BUCKET, 1), null, new ItemStack(Material.STONE_SWORD, 1) , null, null});
        chests.put(new Location(w, -40, 202, 0),   new ItemStack[]{new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), null, new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), null, new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.EMERALD_BLOCK, 16), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD_BLOCK, 16), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), null, new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), null, new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8)});
        chests.put(new Location(w, 40, 202, 0),  new ItemStack[]{new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), null, new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), null, new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.EMERALD_BLOCK, 16), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD_BLOCK, 16), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8), null, new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), new ItemStack(Material.EMERALD, 1), null, new ItemStack(Material.GOLD_INGOT, 8), new ItemStack(Material.GOLD_INGOT, 8)});
        chests.put(new Location(w, -40, 197, 0),   new ItemStack[]{applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2)});
        chests.put(new Location(w, 40, 197, 0),  new ItemStack[]{applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), null, applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.DAMAGE_ALL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_ENVIRONMENTAL, 2), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.KNOCKBACK, 1), applyEnchant(new ItemStack(Material.ENCHANTED_BOOK, 1), Enchantment.PROTECTION_PROJECTILE, 2)});
        chests.put(new Location(w, -26, 197, 14),  new ItemStack[]{applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, applyEffect(new ItemStack(Material.LINGERING_POTION, 1), PotionEffectType.SLOW, 200), null, null, null, null, null, applyEffect(new ItemStack(Material.POTION, 1), PotionEffectType.SPEED, 600), applyEffect(new ItemStack(Material.POTION, 1), PotionEffectType.SPEED, 600), null, null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HARM, 0), null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, null, applyEffect(new ItemStack(Material.LINGERING_POTION, 1), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HARM, 0)});
        chests.put(new Location(w, 26, 197, -14),  new ItemStack[]{applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, applyEffect(new ItemStack(Material.LINGERING_POTION, 1), PotionEffectType.SLOW, 200), null, null, null, null, null, applyEffect(new ItemStack(Material.POTION, 1), PotionEffectType.SPEED, 600), applyEffect(new ItemStack(Material.POTION, 1), PotionEffectType.SPEED, 600), null, null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HARM, 0), null, applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HEAL, 0), null, null, null, applyEffect(new ItemStack(Material.LINGERING_POTION, 1), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.SPLASH_POTION, 1), PotionEffectType.HARM, 0)});
        chests.put(new Location(w, -54, 197, -14),   new ItemStack[]{applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300)});
        chests.put(new Location(w, 54, 197, 14), new ItemStack[]{applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.SLOW, 200), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), applyEffect(new ItemStack(Material.TIPPED_ARROW, 1), PotionEffectType.POISON, 100), null, applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300), applyEffect(new ItemStack(Material.TIPPED_ARROW, 2), PotionEffectType.WEAKNESS, 300)});
    } 
    private static ItemStack applyEnchant(ItemStack stack, Enchantment enchantment, int level) {
        stack.addUnsafeEnchantment(enchantment, level);
        return stack;
    }
    
    private static ItemStack applyEffect(ItemStack stack, PotionEffectType effect, int time) {
        PotionMeta tmpmeta = (PotionMeta) stack.getItemMeta();
        tmpmeta.addCustomEffect(new PotionEffect(effect, time, 0), true);
        stack.setItemMeta(tmpmeta);
        return stack;
    }

    public static void setupChests() {
        for (Entry<Location, ItemStack[]> entrySet : chests.entrySet()) {
            Location loc = entrySet.getKey();
            Block block = loc.getBlock();
            if (block.getType() != Material.CHEST)
                block.setType(Material.CHEST);

            Chest chest = (Chest) block.getState();
            ItemStack[] items = entrySet.getValue();
            for (int i = 0; i < items.length; i++) {
                chest.getInventory().setItem(i, items[i]);
            }
        }
    }

    public static void jankChestRefill() {
        for (val entry : chests.entrySet()) {
            val loc = entry.getKey();
            val inv = entry.getValue();
            val invLength = inv.length;
            
            Block locBlock = world.getBlockAt(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ());
            if (locBlock.getType() != Material.CHEST)
                continue;

            Chest targetChest = (Chest)locBlock.getState();

            ItemStack[] targetChestInventory = targetChest.getInventory().getContents();
            
            // Access the list in a shuffled way.
            List<Integer> indices = new ArrayList<>();
            for (int i = 0; i < targetChestInventory.length; i++) {
                indices.add(i);
            }
            Collections.shuffle(indices);

            for (int i : indices) {
            // for (int i = 0; i < targetChestInventory.length ; i++) {
                ItemStack currentItem = targetChestInventory[i];
                ItemStack exceptedItem = (invLength >= i) ? inv[i] : null; // condition to avoid oob

                if (exceptedItem == null || exceptedItem.equals(currentItem))
                    continue;
            
                if (currentItem == null) {
                    // If no item, set to amount of either 16 (max) or if less than 16 required as much as you can.
                    ItemStack newItem = new ItemStack(exceptedItem);
                    newItem.setAmount(Math.min(newItem.getAmount(), 16));
                    targetChestInventory[i] = newItem;
                    targetChest.getInventory().setContents(targetChestInventory);
                    break;
                } else if (currentItem.getType() == exceptedItem.getType() && currentItem.getAmount() < exceptedItem.getAmount()) {
                    // If already an item but not full, add to current amount:
                    // 16 if needs 16+
                    // exceptedItem.getAmount() - currentItem.getAmount(); if needs less than 16
                    ItemStack newItem = new ItemStack(exceptedItem);
                    int amountNeededUntilmax = exceptedItem.getAmount() - currentItem.getAmount();
                    if (amountNeededUntilmax >= 16)
                        newItem.setAmount(16);
                    else
                        newItem.setAmount(amountNeededUntilmax);
                    targetChestInventory[i] = newItem;
                    targetChest.getInventory().setContents(targetChestInventory);
                    break;
                }
            }
        }
    }
}
